apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: infrastructure
  labels:
    app: keycloak
  name: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  strategy:
    type: Recreate
  template:
    metadata:

      labels:
        app: keycloak
    spec:
      containers:
        - args:
            - start-dev
            - "--http-port=8181"
          env:
            - name: DB_ADDR
              value: mysql
            - name: DB_DATABASE
              value: keycloak
            - name: DB_PASSWORD
              value: password
            - name: DB_USER
              value: keycloak
            - name: DB_VENDOR
              value: MYSQL
            - name: KEYCLOAK_ADMIN
              value: admin
            - name: KEYCLOAK_ADMIN_PASSWORD
              value: admin
          image: quay.io/keycloak/keycloak:25.0.0
          name: keycloak
          ports:
            - containerPort: 8181
          resources: {}
          volumeMounts:
            - mountPath: /opt/keycloak/data/import/
              name: keycloak-claim0
      restartPolicy: Always
      volumes:
        - name: keycloak-claim0
          persistentVolumeClaim:
            claimName: keycloak-claim0
status: {}
---
apiVersion: v1
kind: Service
metadata:
  namespace: infrastructure
  labels:
    app: keycloak
  name: keycloak
spec:
  type: NodePort
  ports:
    - name: "8181"
      port: 8181
      targetPort: 8181
      nodePort: 30001
  selector:
    app: keycloak
status:
  loadBalancer: {}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: infrastructure
  creationTimestamp: null
  labels:
    app: keycloak-claim0
  name: keycloak-claim0
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
