apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: service
  labels:
    app: notification-service
  name: notification-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  strategy: {}
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
        - env:
            - name: MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE
              value: prometheus
            - name: MANAGEMENT_ZIPKIN_TRACING_ENDPOINT
              value: http://zipkin.infrastructure:9411/api/v2/spans
            - name: SPRING_RABBITMQ_HOST
              value: rabbitmq.infrastructure
            - name: SPRING_PROFILES_ACTIVE
              value: docker
          image: vartzy/notification-service:latest
          name: notification-service
          ports:
            - containerPort: 8083
          resources: {}
      restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Service
metadata:
  namespace: service
  labels:
    app: notification-service
  name: notification-service
spec:
  ports:
    - name: "8083"
      port: 8083
      targetPort: 8083
  selector:
    app: notification-service
status:
  loadBalancer: {}
