apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: service
  labels:
    app: order-service
  name: order-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  strategy: {}
  template:
    metadata:

      labels:
        app: order-service
    spec:
      containers:
        - env:
            - name: MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE
              value: prometheus
            - name: MANAGEMENT_ZIPKIN_TRACING_ENDPOINT
              value: http://zipkin.infrastructure:9411/api/v2/spans
            - name: SPRING_RABBITMQ_HOST
              value: rabbitmq.infrastructure
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql-order.infrastructure:3306/order_service
            - name: SPRING_PROFILES_ACTIVE
              value: docker
          image: vartzy/order-service:latest
          name: order-service
          ports:
            - containerPort: 8081
          resources: {}
      restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Service
metadata:
  namespace: service
  labels:
    app: order-service
  name: order-service
spec:
  ports:
    - name: "8081"
      port: 8081
      targetPort: 8081
  selector:
    app: order-service
status:
  loadBalancer: {}
